# name: chat_app
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: ^3.9.2

# dependencies:
#   flutter:
#     sdk: flutter
#   firebase_core: ^4.2.0
#   firebase_auth: ^6.1.1
#   bloc: ^9.1.0
#   hydrated_bloc: ^10.1.1
#   shared_preferences: ^2.5.3
#   cloud_firestore: ^6.0.3
#   flutter_bloc: ^9.1.1
#   modal_progress_hud_nsn: ^0.5.1
#   intl: ^0.20.2
#   image_picker: ^1.2.0
#   supabase_flutter: ^2.10.3
#   meta: ^1.16.0
#   path: ^1.9.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
  



name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  shared_preferences: ^2.5.3
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.20.2
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.3
  meta: ^1.16.0
  path: ^1.9.1
  # firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  path_provider: ^2.1.5
  firebase_storage: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
   